### PR TITLE
v2022.06.0

### PR DESCRIPTION
**Pull request by michaelavs**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by michaelavs** [comment]
I believe this is all that needs to be updated for the new release. The sha56 number was taken from PyPI (which has been successfully updated to 2022.06.0) in accordance to when is listed on [conda-forge/staged-recipes](https://github.com/conda-forge/staged-recipes). Let me know if anything looks incorrect or needs to be done!

**Comment by michaelavs** [comment]
@conda-forge-admin, please rerender

**Comment by erogluorhan** [comment]
The current build test gives SHA256 mismatch error, so please ensure using the SHA256 that you generated from the release of the version you are trying to release here. Even after that, I'd expect to see other issues related to the test-related package dependencies such as netcdf4 (as we discussed and solved with @anissa111 last week on internal tests).

**Comment by michaelavs** [comment]
@erogluorhan Everything is passing now (added the requirements in the last push along with sha256 update) so I think we should be good to go if you want to do an official review

**Review by anissa111 — APPROVED** [review]

**Pull request merged**
